---

#- name: run zookeeper server
#  docker: 
#    docker_api_version: "1.10"
#    name:  Zookeeper
#    image: "{{ ZOOKEEPER_DOCKER_IMAGE_REPO }}"
#    #expose: "{{ ZOOKEEPER_LINKED_PORTS }}"
#    state: running
#  sudo: yes

- name: test if there exists a running zookeeper
  shell: >
    if (docker.io ps -a | grep -q "Up .* {{ zookeeper_container_name }}" ); then
       echo 'running'
    elif (docker.io ps -a | grep -q "Exit .* {{ zookeeper_container_name }}" ); then
       echo 'exited'
    else
       echo 'not running'
    fi
  register: whether_running

#- debug: var=whether_running


- name: clean zookeeper server if it ran before
  shell: docker.io rm "{{ zookeeper_container_name }}"
  when: whether_running.stdout == 'exited'

- name: run zookeeper server
  shell: >
    docker.io run -d
    -p "{{ ZOOKEEPER_PORT1 }}:{{ ZOOKEEPER_PORT1 }}"
    -p "{{ ZOOKEEPER_PORT2 }}:{{ ZOOKEEPER_PORT2 }}"
    -p "{{ ZOOKEEPER_PORT3 }}:{{ ZOOKEEPER_PORT3 }}"
    --name "{{ zookeeper_container_name }}"
    "{{ ZOOKEEPER_DOCKER_IMAGE_REPO }}"
  when: whether_running.stdout != 'running'
