---
- name: update and install wget
  apt: name=wget state=latest update_cache=yes

- name: update and install openjdk
  apt: name=openjdk-7-jre-headless state=latest update_cache=yes

- name: install zookeeper
  shell: >
    wget -q -O - http://apache.mirrors.pair.com/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz | tar -xzf - -C /opt \
    && mv -f /opt/zookeeper-3.4.6 /opt/zookeeper \
    && cp /opt/zookeeper/conf/zoo_sample.cfg /opt/zookeeper/conf/zoo.cfg \
    && mkdir -p /tmp/zookeeper \
    && mkdir -p /var/log/zookeeper

