---

- name: Install Docker daemon on host machines
  apt: name=docker.io state=latest

- name: install easy_install
  apt: name=python-setuptools state=latest

- name: Install docker-py
  easy_install: name=docker-py

- name: Start Docker daemon
  service:  name=docker.io state=started
