---
- name: update and install wget
  apt: name=wget state=latest update_cache=yes

- name: get latest docker
  shell: wget -qO- https://get.docker.com/ | sh

- name: start docker daemon
  service: name=docker state=started
